### ISSUE TITLE
KeySwitch

### ISSUE THREAD

**Issue by joe2k01** [lineage-umi-super/android_device_umi_super#1]
You need to sync https://github.com/joe2k01/KeySwitch/tree/AOSP-build to include the keyswitching app. If you find a better solution please report it

**Comment by deadman96385** [comment]
Yeah my builds are including it, I looked through the stock settings and frameworks and they look like they are doing  pretty much your app just dynamically by letting keylayouts be reloaded without a reboot. If you want to I'd love to talk with you on Hangouts, seanhoyt963@gmail.com
